spring:
  application:
    name: grtblog-backend
  data:
    mongodb:
      uri: mongodb://172.20.0.4:27017/grtblog
  datasource:
    url: jdbc:mysql://172.20.0.3:3306/grtblog?serverTimezone=GMT%2B8&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: user
    password: password
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
      location: /path/to/backend/
  mvc:
    static-path-pattern: /uploads/**
  web:
    resources:
      static-locations: file:/path/to/backend/
  mail:
    host: smtp.larksuite.com
    port: 587
    username: name@example.com
    password: your_password
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.starttls.required: true
    default-encoding: UTF-8
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: your_client_id
            client-secret: your_client_secret
            scope: profile, email
            redirect-uri: "https://your_deploy_site/api/v1/login/oauth2/code/google"
            client-name: Google
          github:
            client-id: your_client_id
            client-secret: your_client_secret
            redirect-uri: "https://your_deploy_site/api/v1/login/oauth2/code/github"
            scope: user:email
            client-name: Github
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub
          github:
            authorization-uri: https://github.com/login/oauth/authorize
            token-uri: https://github.com/login/oauth/access_token
            user-info-uri: https://api.github.com/user
            user-name-attribute: id
    elasticsearch:
      uris: http://localhost:9200
      username:
      password:
#  mvc:
#    servlet:
#      path: /api/v1

# mybatis-plus configuration
mybatis-plus:
  global-config:
    sequence:
      datacenter-id: 1
      worker-id: 1
    db-config:
      id-type: assign_id
  mapper-locations: classpath:mapper/*.xml

# enable log for web request (develop only)
logging:
  #   level:
  #     org:
  #       springframework:
  #         web: DEBUG
  config: classpath:logback-spring.xml

# use at "In extreme cases, the primary key is duplicated."
snowflake:
  data-center-id: 1
  machine-id: 1

com:
  grtsinry43:
    secret_key:  # 这里使用 `openssl rand -base64 64` 生成一个随机字符串用作密钥
    deepseek-api-key: your_api_key
    github:
      clientId: your_client_id
      clientSecret: your_client_secret
      redirectUri: https://your_deploy_site/api/v1/login/oauth2/code/github
    meilisearch:
      url: http://localhost:7700
      apiKey: masterKey

recommender:
  service:
    url: http://172.20.0.7:8001
