spring:
  application:
    name: grtblog-backend
  datasource:
    url: jdbc:mysql://localhost:3306/grtblog?serverTimezone=GMT%2B8&characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
  config:
    import: classpath:application-secret.yml
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
      location: /home/grtsinry43/grtblog/backend/
  mvc:
    static-path-pattern: /uploads/**
  web:
    resources:
      static-locations: file:/home/grtsinry43/grtblog/backend/uploads/
#  mvc:
#    servlet:
#      path: /api/v1

# mybatis-plus configuration
mybatis-plus:
  global-config:
    sequence:
      datacenter-id: 1
      worker-id: 1
    db-config:
      id-type: assign_id
  mapper-locations: classpath:mapper/*.xml

# enable log for web request (develop only)
logging:
  #  level:
  #    com.grtsinry43.grtblog.mapper: DEBUG
  #    org:
  #      springframework:
  #        web: DEBUG
  config: classpath:logback-spring.xml

# use at "In extreme cases, the primary key is duplicated."
snowflake:
  data-center-id: 1
  machine-id: 1

pf4j:
  pluginsDir: plugins